version: '3'

services:
  frontend:
    container_name: frontend
    build: frontend/
    image: frontend
    ports:
      - 8080:80
    depends_on:
      - rabbitmq
    # links:
    #   - backend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  backend:
    container_name: backend-service
    build: backend/service
    image: backend-service
    restart: on-failure
    env_file: .env
    ports:
      - 8765:80
    depends_on:
      - rabbitmq
    # links:
    #   - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  rabbitmq:
    container_name: rabbitmq-service
    build: rabbitmq/
    image: rabbitmq-service    
    healthcheck:
      start_period: 60s
      timeout: 120s
      interval: 30s
      test: ifconfig | grep broadcast
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_VHOST: amqp
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_NODE_TYPE: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - r_data:/var/lib/rabbitmq/data
      - r_logs:/var/log/rabbitmq/log
      
  servicedb:
    container_name: fastapi-service
    build: servicedb/service
    image: servicedb-fastapi
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PYTHONUNBUFFERED: 1
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - 8000:80
    depends_on:
      - rabbitmq
      - db
    # links:
    #   - rabbitmq
    #   - db

  db:
    container_name: db
    build: db/
    image: db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./.database_data:/var/lib/postgresql/data


volumes:
  r_data:
    driver: local
  r_logs:
    driver: local
  .database_data:
    driver: local
