version: '3'

services:
  frontend:
    container_name: frontend
    build: frontend/
    image: frontend
    ports:
      - 8080:80
    depends_on:
      - rabbitmq
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  backend:
    container_name: backend-service
    build: backend/service
    image: backend-service
    restart: on-failure
    env_file: .env
    ports:
      - 8765:80
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  # rabbitmq:
  #   container_name: rabbitmq-service
  #   build: rabbitmq/
  #   image: rabbitmq-service 
  #   restart: always   
  #   healthcheck:
  #     test: rabbitmq-diagnostics -q ping
  #     interval: 10s
  #     timeout: 10s
  #   env_file: .env
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  #     RABBITMQ_NODE_TYPE: rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   volumes:
  #     - r_data:/var/lib/rabbitmq/data
  #     - r_logs:/var/log/rabbitmq/log
  rabbitmq:
    hostname: rabbitmq1
    container_name: rabbitmq-service1
    build: rabbitmq/
    image: rabbitmq-service  # 
    # restart: always   
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_NODE_TYPE: rabbitmq
      # RABBITMQ_PID_FILE: /var/lib/rabbitmq/mnesia/rabbitmq
      # RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq
      # RABBITMQ_ERLANG_COOKIE: 1234
      RABBITMQ_NODENAME: node1
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - r_data:/var/lib/rabbitmq/data
    #   - r_logs:/var/log/rabbitmq/log
    

  rabbitmq2:
    hostname: rabbitmq2
    container_name: rabbitmq-service2
    build: rabbitmq/
    image: rabbitmq-service  # 
    # restart: always   
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_NODE_TYPE: rabbitmq
      # RABBITMQ_PID_FILE: /var/lib/rabbitmq/mnesia/rabbitmq
      # RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq
      # RABBITMQ_ERLANG_COOKIE: 1234
      RABBITMQ_NODENAME: node2
    ports:
      - 5673:5672
      - 15673:15672
    # volumes:
    #   - r_data:/var/lib/rabbitmq/data
    #   - r_logs:/var/log/rabbitmq/log
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: /usr/local/bin/cluster_entrypoint.sh
      
  servicedb:
    container_name: servicedb
    build: servicedb/service
    image: servicedb-fastapi
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PYTHONUNBUFFERED: 1
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - 8000:80
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy

  db:
    container_name: db
    build: db/
    image: db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'"]
      interval: 10s
      timeout: 5s
    volumes:
      - ./.database_data:/var/lib/postgresql/data


volumes:
  r_data:
    driver: local
  r_logs:
    driver: local
  .database_data:
    driver: local
